@startuml
scale 10 as 100 pixels

clock "sampling interval" as interval with period 5 pulse 1
binary "signal1" as signal1
binary "state1" as state1
binary "signal2" as signal2
binary "state2" as state2
binary "signal3" as signal3
binary "state3" as state3

@0
signal2 is high
state2 is high
@7
state3 -> signal3 : pressed
signal3 is {0,1}
@9
signal3 is high
@10
state1 -> signal1 : pressed
signal1 is {0,1}
@18
signal1 is high
@20
signal1 -> state1 : detect pressing
state1 is high
signal2 -> state2 : repeat-1
signal3 -> state3 : click-1
state3 is high
@24
signal3 is {0,1}
@29
signal3 is low
@35
state3 is low
@38
signal3 is {0,1}
@40
signal2 -> state2 : repeat-2
signal3 is high
@50
signal1 -> state1 : holding
state3 is high
signal3 -> state3 : click-2
@58
state1 -> signal1 : released
signal1 is {0,1}
@60
signal2 -> state2 : repeat-3
@67
signal1 is low
@69
state2 -> signal2 : released
signal2 is {0,1}
@70
signal1 -> state1 : detect releasing
state1 is low
@72
signal2 is low
@80
signal2 -> state2 : detect releasing
state2 is low
signal3 -> state3 : holding
@enduml
