# SPDX-License-Identifier: MIT

execute_process(
	COMMAND git describe --long --tags --dirty --always
	WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
	OUTPUT_VARIABLE VERSION
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

string(REPLACE "-" ";" VERSION_STR ${VERSION})
list(GET VERSION_STR 0 VERSION_NUMBER)
string(REPLACE "v" "" VERSION_NUMBER_LIST ${VERSION_NUMBER})
string(REPLACE "." ";" VERSION_NUMBER_LIST ${VERSION_NUMBER_LIST})
list(GET VERSION_NUMBER_LIST 0 MAJOR_NUMBER)

list(LENGTH VERSION_NUMBER_LIST VERSION_NUMBER_LIST_COUNT)

if (${VERSION_NUMBER_LIST_COUNT} GREATER_EQUAL 2)
list(GET VERSION_NUMBER_LIST 1 MINOR_NUMBER)
list(GET VERSION_STR 1 PATCH_NUMBER)
endif()

if (${VERSION_NUMBER_LIST_COUNT} GREATER_EQUAL 3)
	list(GET VERSION_NUMBER_LIST 2 BUILD_NUMBER_ORG)
	MATH(EXPR PATCH_NUMBER "${BUILD_NUMBER_ORG} + ${PATCH_NUMBER}")
endif()

set(VERSION_TAG "v${MAJOR_NUMBER}.${MINOR_NUMBER}.${PATCH_NUMBER}")
