name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    container: libmcu/ci:latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build Project
        run: CROSS_COMPILE=arm-none-eabi VERSION=${GITHUB_REF#refs/tags/} make
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=HASH::$(cat build/libmcu_*.sha256)
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.get_version.outputs.HASH }}

            ## Features
            ## Bug Fixes
          draft: false
          prerelease: false
